language: cpp

os:
 - osx
 - linux

sudo: false

branches:
  only:
    - gh-pages
    - /^.*$/

env:
  matrix:
   - NODE_NVM_VERSION="4"
   - NODE_NVM_VERSION="6"
   - NODE_NVM_VERSION="7"

before_install:
 - git clone --depth 1 https://github.com/creationix/nvm.git ../.nvm
 - source ../.nvm/nvm.sh
 - nvm install $NODE_NVM_VERSION
 - nvm use $NODE_NVM_VERSION

install:
 - npm install

before_script:
 - make

script:
 - make test
